all: mainTarget

mainTarget: Tracking.cpp
	g++ Tracking.cpp -o Tracking -lraspicam_cv -lraspicam -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -L/opt/vc/lib -lmmal -lmmal_core -lmmal_util -lopencv_videoio -lopencv_features2d

